type: ode_time

curves:
  # w0 = 0.1
  - equations: ["-s * \\exp(-(\\alpha-\\betta)w)", "c * (1 - w(1+b * \\exp(h * s) * (1 + w))"]
    variable_names: [s, w]
    initial_conditions: [100, 0.1]  # во втором числе указываем значение параметра w_{0}
    params: {c: 0.3, b: 1.0e-12, h: 0.07, alpha: 2, betta: 1}
    t_span: [0, 7]    #в каких пределах изменяется время t
    solver_method: "RK45"
    styles:
      - {color: "blue", linestyle: "-", linewidth: 1.5, label: "s, w₀=0.02"}
      - {color: "blue", linestyle: "--", linewidth: 1.5, label: "w, w₀=0.02"}
  
  # w0 = 0.1
  - equations: ["-s * \\exp(-(\\alpha-\\betta)w)", "c * (1 - w(1+b * \\exp(h * s) * (1 + w))"]
    variable_names: [s, w]
    initial_conditions: [200, 0.1]  # во втором числе указываем значение параметра w_{0}
    params: {c: 0.3, b: 1.0e-12, h: 0.07, alpha: 2, betta: 1}
    t_span: [0, 7]    #в каких пределах изменяется время t
    solver_method: "RK45"
    styles:
      - {color: "red", linestyle: "-", linewidth: 1.5, label: "s, w₀=0.1"}
      - {color: "red", linestyle: "--", linewidth: 1.5, label: "w, w₀=0.1"}
  
  # w0 = 0.1
  - equations: ["-s * \\exp(-(\\alpha-\\betta)w)", "c * (1 - w(1+b * \\exp(h * s) * (1 + w))"]
    variable_names: [s, w]
    initial_conditions: [300, 0.1]  # во втором числе указываем значение параметра w_{0}
    params: {c: 0.3, b: 1.0e-12, h: 0.07, alpha: 2, betta: 1}
    t_span: [0, 7]    #в каких пределах изменяется время t
    solver_method: "RK45"
    styles:
      - {color: "green", linestyle: "-", linewidth: 1.5, label: "s, w₀=0.3"}
      - {color: "green", linestyle: "--", linewidth: 1.5, label: "w, w₀=0.3"}
  
  # w0 = 0.1
  - equations: ["-s * \\exp(-(\\alpha-\\betta)w)", "c * (1 - w(1+b * \\exp(h * s) * (1 + w))"]
    variable_names: [s, w]
    initial_conditions: [400, 0.1]  # во втором числе указываем значение параметра w_{0}
    params: {c: 0.3, b: 1.0e-12, h: 0.07, alpha: 2, betta: 1}
    t_span: [0, 7]    #в каких пределах изменяется время t
    solver_method: "RK45"
    styles:
      - {color: "orange", linestyle: "-", linewidth: 1.5, label: "s, w₀=0.6"}
      - {color: "orange", linestyle: "--", linewidth: 1.5, label: "w, w₀=0.6"}
  
  # w0 = 0.1
  - equations: ["-s * \\exp(-(\\alpha-\\betta)w)", "c * (1 - w(1+b * \\exp(h * s) * (1 + w))"]
    variable_names: [s, w]
    initial_conditions: [500, 0.1]  # во втором числе указываем значение параметра w_{0}
    params: {c: 0.3, b: 1.0e-12, h: 0.07, alpha: 2, betta: 1}
    t_span: [0, 7]    #в каких пределах изменяется время t
    solver_method: "RK45"
    styles:
      - {color: "purple", linestyle: "-", linewidth: 1.5, label: "s, w₀=0.9"}
      - {color: "green", linestyle: "--", linewidth: 1.5, label: "w, w₀=0.9"}

axes:
  xlim: [0,7]
  ylim: [0,500]
  xticks: [0, 2, 4, 5, 6]
  xlabel: "t"
  ylabel: "w"
  grid: false
  spines: #настройка осей, пишем false,если ось не нужна, true - видна
    top: false   
    right: false
    bottom: true
    left: true
  grid_style: #настрйока сетки
    alpha: 0.9  #прозрачность сетки
    linestyle: ":" #стиль сетки 
    linewidth: 1  #толщина сетки
    color: "gray"   #цвет сетки

output: "p28a.svg"